spring.application.name=backend

# ==========================================
# NEON POSTGRESQL
# ==========================================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# SERVER
# ==========================================

server.port=${PORT:8080}    